2.4, added health check for argocd sync step

diff --git a/cd-configs/sensor-release-readiness.yaml b/cd-configs/sensor-release-readiness.yaml
--- a/cd-configs/sensor-release-readiness.yaml
+++ b/cd-configs/sensor-release-readiness.yaml
@@ -80,6 +80,39 @@ spec:
                         - |
                           argocd login argocd-server.argocd.svc --username admin --password dXZIZ5isRj5IIPcJ --insecure
                           argocd app sync toolboxes-jlp-cluster
+
+                          get_health_status() {
+                            argocd app get toolboxes-jlp-cluster -o json | jq -r '.status.health.status'
+                          }
+
+                          # Wait for the application to start progressing
+                          echo "Waiting for the application to start progressing..."
+                          while true; do
+                            STATUS=$(get_health_status)
+                            if [ "$STATUS" == "Progressing" ]; then
+                              echo "Application is progressing..."
+                              break
+                            else
+                              echo "Current status: $STATUS. Waiting..."
+                              sleep 5
+                            fi
+                          done
+
+                          # Wait for the application to become healthy or degraded
+                          echo "Monitoring application health status..."
+                          while true; do
+                            STATUS=$(get_health_status)
+                            if [ "$STATUS" == "Healthy" ]; then
+                              echo "Application is healthy. Sync successful."
+                              break
+                            elif [ "$STATUS" == "Degraded" ]; then
+                              echo "Application is degraded. Exiting with failure."
+                              exit 1
+                            else
+                              echo "Current status: $STATUS. Waiting..."
+                              sleep 5
+                            fi
+                          done
                   - name: argo-rollout-status
                     container:
                       image: jbavuluri/argo-rollouts-custom-image:latest
